// Copyright 2024 Stellar-K8s Contributors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//! StellarTestnet Custom Resource Definition
//!
//! The `StellarTestnet` CRD automates the rapid provisioning and teardown of
//! ephemeral, single-node Stellar testnets inside a Kubernetes cluster.  Each
//! instance spins up a Stellar Core standalone node (memory-backed ledger) plus
//! an optional Soroban RPC sidecar, together with a Kubernetes `Service` and
//! optional `Ingress` that expose the RPC endpoint.  Connection URLs are written
//! back into the `.status` field so CI/CD pipelines can discover them without
//! external coordination.
//!
//! # Key Types
//!
//! - [`StellarTestnet`]       – The CRD root resource (generated by `#[derive(CustomResource)]`)
//! - [`StellarTestnetSpec`]   – Desired configuration (genesis, funded accounts, images, …)
//! - [`StellarTestnetStatus`] – Observed state (phase, RPC URL, funded addresses, …)
//!
//! # Genesis & Pre-funded Accounts
//!
//! The operator synthesises a `stellar-core.cfg` at reconcile time using the
//! values from [`GenesisConfig`].  For every entry in
//! [`StellarTestnetSpec::funded_accounts`] the operator creates a
//! pre-funded key-pair and writes the public keys into
//! [`StellarTestnetStatus::funded_public_keys`] and the secrets into a
//! per-testnet Kubernetes `Secret` named `<name>-funded-keys`.
//!
//! # Garbage Collection
//!
//! The CRD is registered with an owner-reference finalizer
//! (`stellar.org/testnet-cleanup`).  When the resource is deleted the
//! provisioner removes the `Pod`, `Service`, optional `Ingress`, and the
//! funded-keys `Secret` before releasing the finalizer.
//!
//! # Example Manifest
//!
//! ```yaml
//! apiVersion: stellar.org/v1alpha1
//! kind: StellarTestnet
//! metadata:
//!   name: my-testnet
//!   namespace: ci
//! spec:
//!   genesisConfig:
//!     networkPassphrase: "Test SCP Network ; September 2015"
//!     initialLedger: 2
//!     targetLedgerTime: 1
//!   fundedAccounts:
//!     - name: deployer
//!       balanceXlm: 10000
//!     - name: user1
//!       balanceXlm: 5000
//!   sorobanRpc:
//!     enabled: true
//!   ttlSeconds: 1800
//! ```

use kube::CustomResource;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

// ---------------------------------------------------------------------------
// Genesis Configuration
// ---------------------------------------------------------------------------

/// Genesis ledger configuration for the ephemeral Stellar Core standalone node.
#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema)]
#[serde(rename_all = "camelCase")]
pub struct GenesisConfig {
    /// SCP network passphrase written into `stellar-core.cfg`.
    /// Defaults to a unique ephemeral passphrase derived from the resource name.
    #[serde(
        default = "default_network_passphrase",
        skip_serializing_if = "Option::is_none"
    )]
    pub network_passphrase: Option<String>,

    /// First ledger sequence number (must be ≥ 2).
    #[serde(default = "default_initial_ledger")]
    pub initial_ledger: u32,

    /// Target close time between ledgers in seconds (1–60).
    /// Lower values speed up CI tests at the cost of CPU.
    #[serde(default = "default_target_ledger_time")]
    pub target_ledger_time: u32,

    /// Maximum number of operations per transaction (defaults to 100).
    #[serde(default = "default_max_tx_size")]
    pub max_tx_size: u32,
}

fn default_network_passphrase() -> Option<String> {
    None // provisioner generates one from the resource name
}

fn default_initial_ledger() -> u32 {
    2
}

fn default_target_ledger_time() -> u32 {
    1
}

fn default_max_tx_size() -> u32 {
    100
}

impl Default for GenesisConfig {
    fn default() -> Self {
        Self {
            network_passphrase: None,
            initial_ledger: default_initial_ledger(),
            target_ledger_time: default_target_ledger_time(),
            max_tx_size: default_max_tx_size(),
        }
    }
}

// ---------------------------------------------------------------------------
// Pre-funded Account
// ---------------------------------------------------------------------------

/// A named test account that should be pre-funded at genesis.
///
/// The operator generates an Ed25519 key-pair for each entry, writes the
/// public keys into `status.fundedPublicKeys`, and stores the secret keys in
/// the Kubernetes Secret `<testnet-name>-funded-keys`.
#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema)]
#[serde(rename_all = "camelCase")]
pub struct FundedAccount {
    /// Logical name for this account (used as key in the funded-keys Secret).
    pub name: String,

    /// Initial XLM balance in stroops ×10⁻⁷ (i.e. `10000` = 10 000 XLM).
    #[serde(default = "default_balance_xlm")]
    pub balance_xlm: u64,
}

fn default_balance_xlm() -> u64 {
    10_000
}

// ---------------------------------------------------------------------------
// Soroban RPC Sidecar
// ---------------------------------------------------------------------------

/// Configuration for the Soroban RPC sidecar container.
#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema)]
#[serde(rename_all = "camelCase")]
pub struct SorobanRpcConfig {
    /// Enable the Soroban RPC sidecar (defaults to `true`).
    #[serde(default = "default_true")]
    pub enabled: bool,

    /// Container image for the Soroban RPC server.
    /// Defaults to `stellar/soroban-rpc:latest`.
    #[serde(default = "default_soroban_image")]
    pub image: String,

    /// Port the Soroban RPC server listens on inside the Pod (defaults to 8000).
    #[serde(default = "default_rpc_port")]
    pub port: u16,

    /// Additional environment variables injected into the Soroban RPC container.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub extra_env: BTreeMap<String, String>,
}

fn default_true() -> bool {
    true
}

fn default_soroban_image() -> String {
    "stellar/soroban-rpc:latest".to_string()
}

fn default_rpc_port() -> u16 {
    8000
}

impl Default for SorobanRpcConfig {
    fn default() -> Self {
        Self {
            enabled: true,
            image: default_soroban_image(),
            port: default_rpc_port(),
            extra_env: BTreeMap::new(),
        }
    }
}

// ---------------------------------------------------------------------------
// Ingress Configuration
// ---------------------------------------------------------------------------

/// Optional Kubernetes `Ingress` configuration for external access to the RPC.
#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema)]
#[serde(rename_all = "camelCase")]
pub struct TestnetIngressConfig {
    /// Enable creation of a Kubernetes `Ingress` resource.
    #[serde(default)]
    pub enabled: bool,

    /// Ingress class name (e.g. `nginx`, `traefik`).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ingress_class_name: Option<String>,

    /// Hostname to expose the RPC endpoint on.
    /// When set, the operator writes `https://<host>/` into
    /// `status.rpcUrl`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,

    /// Additional annotations applied to the `Ingress` object.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub annotations: BTreeMap<String, String>,
}

impl Default for TestnetIngressConfig {
    fn default() -> Self {
        Self {
            enabled: false,
            ingress_class_name: None,
            host: None,
            annotations: BTreeMap::new(),
        }
    }
}

// ---------------------------------------------------------------------------
// Resource Requirements
// ---------------------------------------------------------------------------

/// Minimal CPU/memory requests for the Stellar Core pod.
#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema)]
#[serde(rename_all = "camelCase")]
pub struct TestnetResources {
    /// CPU request/limit string (e.g. `"500m"`).
    #[serde(default = "default_cpu")]
    pub cpu: String,

    /// Memory request/limit string (e.g. `"512Mi"`).
    #[serde(default = "default_memory")]
    pub memory: String,
}

fn default_cpu() -> String {
    "500m".to_string()
}

fn default_memory() -> String {
    "512Mi".to_string()
}

impl Default for TestnetResources {
    fn default() -> Self {
        Self {
            cpu: default_cpu(),
            memory: default_memory(),
        }
    }
}

// ---------------------------------------------------------------------------
// Main Spec
// ---------------------------------------------------------------------------

/// Specification for a `StellarTestnet` resource.
#[derive(CustomResource, Clone, Debug, Deserialize, Serialize, JsonSchema)]
#[kube(
    group = "stellar.org",
    version = "v1alpha1",
    kind = "StellarTestnet",
    namespaced,
    status = "StellarTestnetStatus",
    shortname = "stnet",
    printcolumn = r#"{"name":"Phase","type":"string","jsonPath":".status.phase"}"#,
    printcolumn = r#"{"name":"RPC URL","type":"string","jsonPath":".status.rpcUrl"}"#,
    printcolumn = r#"{"name":"TTL","type":"integer","jsonPath":".spec.ttlSeconds"}"#,
    printcolumn = r#"{"name":"Age","type":"date","jsonPath":".metadata.creationTimestamp"}"#
)]
#[serde(rename_all = "camelCase")]
pub struct StellarTestnetSpec {
    /// Genesis ledger parameters.
    #[serde(default)]
    pub genesis_config: GenesisConfig,

    /// Named accounts to pre-fund at genesis.
    /// The operator generates key-pairs and stores them in a per-testnet Secret.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub funded_accounts: Vec<FundedAccount>,

    /// Soroban RPC sidecar configuration.
    #[serde(default)]
    pub soroban_rpc: SorobanRpcConfig,

    /// Optional Kubernetes `Ingress` configuration for external RPC access.
    #[serde(default)]
    pub ingress: TestnetIngressConfig,

    /// Container image for Stellar Core standalone.
    /// Defaults to `stellar/stellar-core:latest`.
    #[serde(default = "default_core_image")]
    pub stellar_core_image: String,

    /// CPU and memory resource requests for the Stellar Core pod.
    #[serde(default)]
    pub resources: TestnetResources,

    /// Time-to-live in seconds after which the operator will delete this
    /// `StellarTestnet` automatically.  Set to `0` to disable auto-deletion.
    /// Defaults to `3600` (1 hour).
    #[serde(default = "default_ttl")]
    pub ttl_seconds: u64,

    /// Additional labels applied to all Kubernetes objects owned by this testnet.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub labels: BTreeMap<String, String>,
}

fn default_core_image() -> String {
    "stellar/stellar-core:latest".to_string()
}

fn default_ttl() -> u64 {
    3600
}

// ---------------------------------------------------------------------------
// Status
// ---------------------------------------------------------------------------

/// Phase of a `StellarTestnet` resource.
#[derive(Clone, Debug, Default, Deserialize, Serialize, JsonSchema, PartialEq, Eq)]
#[serde(rename_all = "PascalCase")]
pub enum TestnetPhase {
    /// The operator has accepted the resource and is provisioning it.
    #[default]
    Provisioning,
    /// Stellar Core is running and the Soroban RPC endpoint is reachable.
    Ready,
    /// The testnet has exceeded its TTL and is being torn down.
    Terminating,
    /// Provisioning failed; see `conditions` for details.
    Failed,
}

/// Status sub-resource for a `StellarTestnet`.
#[derive(Clone, Debug, Default, Deserialize, Serialize, JsonSchema)]
#[serde(rename_all = "camelCase")]
pub struct StellarTestnetStatus {
    /// High-level lifecycle phase.
    #[serde(default)]
    pub phase: TestnetPhase,

    /// Soroban JSON-RPC endpoint URL, e.g. `http://<service>.<ns>.svc:8000`.
    /// Populated once the pod reaches `Running` and the RPC health-check passes.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rpc_url: Option<String>,

    /// Stellar Core HTTP management endpoint (internal cluster URL).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub core_url: Option<String>,

    /// SCP network passphrase in use (derived or user-supplied).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub network_passphrase: Option<String>,

    /// Map of `account-name → Stellar public key (G…)` for pre-funded accounts.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub funded_public_keys: BTreeMap<String, String>,

    /// Name of the Kubernetes Secret holding private keys for funded accounts.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub funded_keys_secret: Option<String>,

    /// Human-readable message describing the current operator action.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,

    /// Unix timestamp (seconds) when the testnet will expire based on `ttlSeconds`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<i64>,

    /// ISO-8601 timestamp of the last successful reconcile.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_reconciled_at: Option<String>,

    /// List of Kubernetes conditions for this testnet.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub conditions: Vec<TestnetCondition>,
}

/// A single condition on a `StellarTestnet` resource.
#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema)]
#[serde(rename_all = "camelCase")]
pub struct TestnetCondition {
    /// Condition type (e.g. `Ready`, `CoreRunning`, `RpcReachable`).
    #[serde(rename = "type")]
    pub condition_type: String,

    /// `True`, `False`, or `Unknown`.
    pub status: String,

    /// Machine-readable reason code.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,

    /// Human-readable description.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,

    /// ISO-8601 timestamp of the last state transition.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_transition_time: Option<String>,
}
